/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rm5248_serial_SerialPort */

#ifndef _Included_com_rm5248_serial_SerialPort
#define _Included_com_rm5248_serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    openPort
 * Signature: (Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_openPort__Ljava_lang_String_2IIIII
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    openPort
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_openPort__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    doClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rm5248_serial_SerialPort_doClose
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    setBaudRate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rm5248_serial_SerialPort_setBaudRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getBaudRateInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getBaudRateInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    setStopBits
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rm5248_serial_SerialPort_setStopBits
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getStopBitsInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getStopBitsInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    setCharSize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rm5248_serial_SerialPort_setCharSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getCharSizeInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getCharSizeInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    setParity
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rm5248_serial_SerialPort_setParity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getParityInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getParityInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    setFlowControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rm5248_serial_SerialPort_setFlowControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getFlowControlInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getFlowControlInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getSerialLineStateInternalNonblocking
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getSerialLineStateInternalNonblocking
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    setSerialLineStateInternal
 * Signature: (Lcom/rm5248/serial/SerialLineState;)I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_setSerialLineStateInternal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getMajorNativeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getMajorNativeVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getMinorNativeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SerialPort_getMinorNativeVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_rm5248_serial_SerialPort
 * Method:    getSerialPorts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_rm5248_serial_SerialPort_getSerialPorts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
