/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rm5248_serial_SimpleSerialInputStream */

#ifndef _Included_com_rm5248_serial_SimpleSerialInputStream
#define _Included_com_rm5248_serial_SimpleSerialInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rm5248_serial_SimpleSerialInputStream_MAX_SKIP_BUFFER_SIZE
#define com_rm5248_serial_SimpleSerialInputStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     com_rm5248_serial_SimpleSerialInputStream
 * Method:    readByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SimpleSerialInputStream_readByte
  (JNIEnv *, jobject);

/*
 * Class:     com_rm5248_serial_SimpleSerialInputStream
 * Method:    getAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rm5248_serial_SimpleSerialInputStream_getAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
