/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rm5248_serial_SerialOutputStream */

#ifndef _Included_com_rm5248_serial_SerialOutputStream
#define _Included_com_rm5248_serial_SerialOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rm5248_serial_SerialOutputStream
 * Method:    writeByte
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rm5248_serial_SerialOutputStream_writeByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rm5248_serial_SerialOutputStream
 * Method:    writeByteArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_rm5248_serial_SerialOutputStream_writeByteArray
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
