package com.rm5248.serial;

/**
 * This exception is thrown when the device that you have opened is not a serial port.
 * 
 * @author rm5248
 *
 */
public class NotASerialPortException extends Exception {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 5606767768689212862L;

	/** Create a new exception if this is not a serial port 
	 * 
	 * @param message
	 */
	public NotASerialPortException( String message ){
		super( message );
	}
}
